[colors.bright]
black = "0xfdf6e3"
blue = "0x657b83"
cyan = "0x586e75"
green = "0x93a1a1"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0x002b36"
yellow = "0x839496"

[colors.cursor]
cursor = "0xeee8d5"
text = "0xeee8d5"

[colors.normal]
black = "0xeee8d5"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0x073642"
yellow = "0xb58900"

[colors.primary]
background = "0x073642"
foreground = "0x93a1a1"

[colors.hints.start]
background = "0xd33682"
foreground = "0xffffff"

[colors.hints.end]
background = "0xd33682"
foreground = "0xffffff"
