# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "licensezero-jurisdictions-1.0.1" = {
      name = "licensezero-jurisdictions";
      packageName = "licensezero-jurisdictions";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/licensezero-jurisdictions/-/licensezero-jurisdictions-1.0.1.tgz";
        sha512 = "WJ8l9/tZFyfD6LI9wzddd6bkrS6K1dnLotfEf/dP+Q633Bx/dVqLGNb5ExDv/qE6Tml/VUKIg47K9AtMFuzMnQ==";
      };
    };
  };
  args = {
    name = "licensezerojs";
    packageName = "licensezerojs";
    version = "0";
    src = ./.;
    dependencies = [
      sources."licensezero-jurisdictions-1.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}